### ISSUE TITLE
encode.so python版本兼容性问题

### ISSUE THREAD

**Issue by jijianghui** [Netease-Games-AI-Lab-Guangzhou/PerfectDou#10]
系统版本：Ubuntu 22.04.3 LTS
colab上面测试和本地出现的错误是一样的
torch：       2.5.0+cu121
onnxruntime-gpu   1.20.0

执行python3 evaluate.py --landlord perfectdou --landlord_up douzero --landlord_down douzero
出现ImportError: /content/PerfectDou/perfectdou/env/encode.so: undefined symbol: _Py_CheckRecursionLimit
怀疑是encode.so(已经改名)python版本兼容性的问题？[https://github.com/python/cpython/pull/22359]

另外，**encode.so的代码是否方便开源解决兼容性的问题，如不方便开源能否提供arm的版本移植到mobile phone测试**
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 40, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 21, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "/content/PerfectDou/perfectdou/evaluation/perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ImportError: /content/PerfectDou/perfectdou/env/encode.so: undefined symbol: _Py_CheckRecursionLimit
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 40, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 21, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "/content/PerfectDou/perfectdou/evaluation/perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ImportError: /content/PerfectDou/perfectdou/env/encode.so: undefined symbol: _Py_CheckRecursionLimit
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 40, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 21, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "/content/PerfectDou/perfectdou/evaluation/perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ImportError: /content/PerfectDou/perfectdou/env/encode.so: undefined symbol: _Py_CheckRecursionLimit
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 40, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 21, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "/content/PerfectDou/perfectdou/evaluation/perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ImportError: /content/PerfectDou/perfectdou/env/encode.so: undefined symbol: _Py_CheckRecursionLimit
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 40, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "/content/PerfectDou/perfectdou/evaluation/simulation.py", line 21, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "/content/PerfectDou/perfectdou/evaluation/perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ImportError: /content/PerfectDou/perfectdou/env/encode.so: undefined symbol: _Py_CheckRecursionLimit

**Comment by jijianghui** [comment]
python3.9版本测试已无问题，encode代码能否开源或者提供arm的版本移植到手机上

**Comment by initial-h** [comment]
> python3.9版本测试已无问题，encode代码能否开源或者提供arm的版本移植到手机上

@jijianghui 请问3.9需要调整哪些代码吗，我Python 3.9.21 torch 2.4.1+cu121 onnxruntime==1.7.0 报错ModuleNotFoundError: No module named 'perfectdou.env.encode'
