### ISSUE TITLE
No module named'perfectdou.env.encode'

### ISSUE THREAD

**Issue by mosqudoo** [Netease-Games-AI-Lab-Guangzhou/PerfectDou#5]
pls help me from these question

`PS C:\Users\Administrator\Desktop\temp\work\PerfectDou> python evaluate.py --landlord perfectdou --landlord_up perfectdou --landlord_down perfectdou --eval_data .\start.pkl
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 39, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 20, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ModuleNotFoundError: No module named 'perfectdou.env.encode'
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 39, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 20, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ModuleNotFoundError: No module named 'perfectdou.env.encode'
Process SpawnProcess-3:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 39, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 20, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ModuleNotFoundError: No module named 'perfectdou.env.encode'
Process SpawnProcess-4:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 39, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 20, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ModuleNotFoundError: No module named 'perfectdou.env.encode'
Process SpawnProcess-5:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 39, in mp_simulate
    players = load_card_play_models(card_play_model_path_dict)
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\simulation.py", line 20, in load_card_play_models
    from .perfectdou_agent import PerfectDouAgent
  File "C:\Users\Administrator\Desktop\temp\work\PerfectDou\perfectdou\evaluation\perfectdou_agent.py", line 4, in <module>
    from perfectdou.env.encode import (
ModuleNotFoundError: No module named 'perfectdou.env.encode'`

**Comment by Ericonaldo** [comment]
Seems the problem is due to the mismatch of the platform. The compiled library (.so) only works on Ubuntu with python 3.7. And I think you are using Windows.

**Comment by mosqudoo** [comment]
> 
I’ll try to run it on Ubuntu and thanks for your help

**Comment by guoxh9017** [comment]
I want to be able to run the program on windows. Can I get the corresponding compiled library?
